### ISSUE TITLE
option to utilise existing zookeeper deployment

### ISSUE THREAD

**Issue by madeinoz67** [AlexsJones/nifi#1]
Is there a possibility to utilise an existing zookeeper deployment with this helm chart rather than deploying ZK as part of this chart?  i.e. I'm looking at deploying this on an existing kafka cluster (Strimzi) for staging purposes and this already has zookeeper deployed.

**Comment by AlexsJones** [comment]
Yeah I can sort that out for sure

**Comment by AlexsJones** [comment]
https://github.com/AlexsJones/nifi/commit/183c96cb8daedcfac57167a2ad118dcfcd26072f

This is resolved please pull latest.

**Comment by madeinoz67** [comment]
cheers nothing like first of the board :D
