### ISSUE TITLE
Use the official NiFi Image.

### ISSUE THREAD

**Issue by juliofalbo** [AlexsJones/nifi#5]
Hi, first of all, thanks for this repo!

My only concern is about the NiFi image that you are using.

Would be possible to change `xemuliam/nifi` to `apache/nifi:latest` or `apache/nifi:1.12.0-SNAPSHOT-dockermaven`?

**Comment by AlexsJones** [comment]
Sure thing just set that in helm

```
--set=image.repository=apache/nifi
```
