### ISSUE TITLE
Use Zookeeper docker image instead of Zookeeper tgz

### ISSUE THREAD

**Issue by juliofalbo** [AlexsJones/nifi#6]
Hi Alexs.

Is it possible to use a zookeeper image like `bitnami/zookeeper:latest` instead of the tgz?

**Comment by AlexsJones** [comment]
Done, I've updated it to an actual chart and updated the readme. You can do this 
`helm install nifi . --namespace=nifi --set=.Values.zookeeper.image.repository=foo --dry-run` as an example
